"""
Role-Based Access Control (RBAC) permissions module for CRM.
Defines role permission sets, permission checking, and the @require_permission decorator.
"""
from functools import wraps
from rest_framework.response import Response
from rest_framework import status


ROLE_PERMISSIONS = {
    "admin": {
        "account.create",
        "account.delete",
        "account.edit",
        "account.view",
        "call.create",
        "call.delete",
        "call.dial",
        "call.edit",
        "call.view",
        "case.create",
        "case.delete",
        "case.edit",
        "case.view",
        "casesolution.create",
        "casesolution.delete",
        "casesolution.edit",
        "casesolution.view",
        "customer.create",
        "customer.delete",
        "customer.edit",
        "customer.view",
        "deal.create",
        "deal.delete",
        "deal.edit",
        "deal.view",
        "integration.manage",
        "integration.view",
        "invoice.create",
        "invoice.delete",
        "invoice.edit",
        "invoice.view",
        "lead.convert",
        "lead.create",
        "lead.delete",
        "lead.edit",
        "lead.view",
        "meeting.create",
        "meeting.delete",
        "meeting.edit",
        "meeting.view",
        "picklist.create",
        "picklist.delete",
        "picklist.edit",
        "picklist.view",
        "pricebook.create",
        "pricebook.delete",
        "pricebook.edit",
        "pricebook.view",
        "product.create",
        "product.delete",
        "product.edit",
        "product.view",
        "purchaseorder.create",
        "purchaseorder.delete",
        "purchaseorder.edit",
        "purchaseorder.view",
        "quote.create",
        "quote.delete",
        "quote.edit",
        "quote.view",
        "report.export",
        "report.view",
        "salesorder.create",
        "salesorder.delete",
        "salesorder.edit",
        "salesorder.view",
        "service.create",
        "service.delete",
        "service.edit",
        "service.view",
        "staff.create",
        "staff.delete",
        "staff.edit",
        "staff.view",
        "task.create",
        "task.delete",
        "task.edit",
        "task.view",
        "twilio.manage",
        "twilio.view",
        "vendor.create",
        "vendor.delete",
        "vendor.edit",
        "vendor.view",
    },
    "manager": {
        "account.create",
        "account.delete",
        "account.edit",
        "account.view",
        "call.create",
        "call.delete",
        "call.dial",
        "call.edit",
        "call.view",
        "case.create",
        "case.delete",
        "case.edit",
        "case.view",
        "casesolution.create",
        "casesolution.delete",
        "casesolution.edit",
        "casesolution.view",
        "customer.create",
        "customer.delete",
        "customer.edit",
        "customer.view",
        "deal.create",
        "deal.delete",
        "deal.edit",
        "deal.view",
        "invoice.create",
        "invoice.delete",
        "invoice.edit",
        "invoice.view",
        "lead.convert",
        "lead.create",
        "lead.delete",
        "lead.edit",
        "lead.view",
        "meeting.create",
        "meeting.delete",
        "meeting.edit",
        "meeting.view",
        "picklist.view",
        "pricebook.create",
        "pricebook.delete",
        "pricebook.edit",
        "pricebook.view",
        "product.create",
        "product.delete",
        "product.edit",
        "product.view",
        "purchaseorder.create",
        "purchaseorder.delete",
        "purchaseorder.edit",
        "purchaseorder.view",
        "quote.create",
        "quote.delete",
        "quote.edit",
        "quote.view",
        "report.export",
        "report.view",
        "salesorder.create",
        "salesorder.delete",
        "salesorder.edit",
        "salesorder.view",
        "service.create",
        "service.delete",
        "service.edit",
        "service.view",
        "staff.create",
        "staff.edit",
        "staff.view",
        "task.create",
        "task.delete",
        "task.edit",
        "task.view",
        "vendor.create",
        "vendor.delete",
        "vendor.edit",
        "vendor.view",
    },
    "sales agent": {
        "account.create",
        "account.edit",
        "account.view",
        "call.create",
        "call.dial",
        "call.view",
        "customer.create",
        "customer.edit",
        "customer.view",
        "deal.create",
        "deal.edit",
        "deal.view",
        "invoice.view",
        "lead.convert",
        "lead.create",
        "lead.edit",
        "lead.view",
        "meeting.create",
        "meeting.edit",
        "meeting.view",
        "picklist.view",
        "pricebook.view",
        "product.view",
        "quote.view",
        "report.view",
        "salesorder.view",
        "service.view",
        "task.create",
        "task.edit",
        "task.view",
    },
    "support agent": {
        "account.view",
        "call.create",
        "call.dial",
        "call.view",
        "case.create",
        "case.edit",
        "case.view",
        "casesolution.create",
        "casesolution.edit",
        "casesolution.view",
        "customer.edit",
        "customer.view",
        "deal.view",
        "lead.view",
        "meeting.create",
        "meeting.edit",
        "meeting.view",
        "picklist.view",
        "product.view",
        "report.view",
        "service.view",
        "task.create",
        "task.edit",
        "task.view",
    },
}


def has_permission(staff, perm: str) -> bool:
    """
    Check if a staff member has the given permission.
    Staff.role is the source of truth.
    """
    if not staff or not getattr(staff, "role", None):
        return False
    role = staff.role.strip().lower()
    if role == "admin":
        return True
    return perm in ROLE_PERMISSIONS.get(role, set())


def require_permission(perm: str):
    """
    Decorator for API view functions.
    Checks if the authenticated staff member has the required permission.
    Returns standard 403 Forbidden Response if unauthorized.
    """
    def decorator(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            staff = getattr(request, "staff", None)
            if not staff:
                user = getattr(request, "user", None)
                if user and hasattr(user, "staff"):
                    staff = user.staff

            if not has_permission(staff, perm):
                return Response(
                    {
                        "detail": "You do not have permission to perform this action.",
                        "message": "You do not have permission to perform this action.",
                    },
                    status=status.HTTP_403_FORBIDDEN,
                )

            return view_func(request, *args, **kwargs)
        return wrapper
    return decorator
