# Generated by Django 6.0.5 on 2026-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('lead_source', models.CharField(choices=[('Website', 'Website'), ('Ads', 'Ads'), ('Referral', 'Referral'), ('WhatsApp', 'WhatsApp')], default='Website', max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('expected_closing_date', models.DateField(blank=True, null=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
