# Generated by Django 6.0.5 on 2026-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
