# Generated by Django 6.0.5 on 2026-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_alter_lead_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('deal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.CharField(choices=[('Discussion', 'Discussion'), ('Demo', 'Demo'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], default='Discussion', max_length=50)),
                ('assigned_to', models.CharField(max_length=255)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('deal_source', models.CharField(choices=[('Website', 'Website'), ('Ads', 'Ads'), ('Referral', 'Referral'), ('WhatsApp', 'WhatsApp')], default='Website', max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('deal_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
