# Generated by Django 6.0.5 on 2026-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_deal_customer_deal_lead_lead_converted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('Website', 'Website'), ('WhatsApp', 'WhatsApp'), ('Facebook Ads', 'Facebook Ads'), ('Google Ads', 'Google Ads'), ('Referral', 'Referral')], default='Website', max_length=50),
        ),
    ]
