# Generated by Django 6.0.5 on 2026-06-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Discussion', 'Discussion'), ('Demo', 'Demo'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='Discussion', max_length=50),
        ),
    ]
