# Generated by Django 6.0.5 on 2026-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_source',
            field=models.CharField(choices=[('Website', 'Website'), ('Ads', 'Ads'), ('Referral', 'Referral'), ('WhatsApp', 'WhatsApp'), ('Google Ads', 'Google Ads'), ('Facebook Ads', 'Facebook Ads')], default='Website', max_length=50),
        ),
    ]
