# Generated by Django 6.0.5 on 2026-06-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales agent', 'Sales agent'), ('support agent', 'Support agent')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('is_invited', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
