# Generated by Django 6.0.5 on 2026-06-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicklistOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('lead_status', 'Lead Status'), ('lead_source', 'Lead Source'), ('lead_priority', 'Lead Priority'), ('deal_stage', 'Deal Stage'), ('deal_source', 'Deal Source'), ('deal_priority', 'Deal Priority'), ('customer_status', 'Customer Status'), ('customer_industry', 'Customer Industry'), ('task_status', 'Task Status'), ('task_priority', 'Task Priority')], max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['field', 'order'],
                'unique_together': {('field', 'value')},
            },
        ),
    ]
