# Generated by Django 6.0.5 on 2026-06-24 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_address_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('quote_stage', models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Negotiation'), ('delivered', 'Delivered'), ('on_hold', 'On Hold'), ('confirmed', 'Confirmed'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='draft', max_length=50)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='AdminApp.accounts')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='AdminApp.staff')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_billing', to='AdminApp.address')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='AdminApp.deal')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_shipping', to='AdminApp.address')),
            ],
        ),
    ]
