# Generated by Django 6.0.5 on 2026-06-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='AdminApp.accounts'),
        ),
    ]
