# Generated by Django 6.0.5 on 2026-06-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_deal_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_closing_date',
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_leads', to='AdminApp.customer'),
        ),
    ]
