# Generated by Django 6.0.5 on 2026-06-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0012_remove_deal_lead_remove_lead_expected_closing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('list_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage or Fixed amount', max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.quotes')),
            ],
        ),
    ]
