# Generated by Django 6.0.5 on 2026-06-27 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_quoteproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='account',
        ),
        migrations.AddField(
            model_name='quotes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='AdminApp.customer'),
        ),
    ]
