# Generated by Django 6.0.5 on 2026-06-29 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0015_remove_quotes_customer_quotes_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_venue', models.CharField(choices=[('online', 'Online'), ('client_location', 'Client Location'), ('in_office', 'In-Office')], default='online', max_length=50)),
                ('provider', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet'), ('microsoft_teams', 'Microsoft Teams'), ('other', 'Other')], default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('all_day', models.BooleanField(default=False)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('related_type', models.CharField(choices=[('none', 'None'), ('lead', 'Lead'), ('customer', 'Customer')], default='none', max_length=20)),
                ('repeat', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_meetings', to='AdminApp.staff')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings', to='AdminApp.staff')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='AdminApp.customer')),
                ('related_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='AdminApp.lead')),
            ],
        ),
    ]
