# Generated by Django 6.0.5 on 2026-07-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0020_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AdminApp.pricebook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_items', to='AdminApp.product')),
            ],
            options={
                'unique_together': {('price_book', 'product')},
            },
        ),
    ]
