# Generated by Django 6.0.5 on 2026-07-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0022_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.product'),
        ),
    ]
