# Generated by Django 6.0.5 on 2026-07-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0025_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='state',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='AdminApp.address'),
        ),
    ]
