# Generated by Django 6.0.5 on 2026-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0027_company_alter_pricebook_name_accounts_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
