# Generated by Django 6.0.5 on 2026-07-09 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0028_staff_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
