# Generated by Django 6.0.5 on 2026-07-09 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0029_staff_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
