# Generated by Django 6.0.5 on 2026-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0031_alter_staff_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='expected_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
