# Generated by Django 6.0.5 on 2026-07-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0032_lead_expected_closing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='AdminApp.lead'),
        ),
    ]
