# Generated by Django 6.0.5 on 2026-07-10 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0033_remove_lead_converted_customer_customer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='AdminApp.lead'),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='AdminApp.lead'),
        ),
    ]
