# Generated by Django 6.0.5 on 2026-07-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0036_casesolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('billing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='fixed', max_length=20)),
                ('duration', models.CharField(blank=True, help_text='Example: 2 Hours, 30 Days, 1 Month', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='AdminApp.company')),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
    ]
