# Generated by Django 6.0.5 on 2026-07-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0037_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteproduct',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.service'),
        ),
    ]
