# Generated by Django 6.0.5 on 2026-07-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0039_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='added_by',
        ),
    ]
