# Generated by Django 6.0.5 on 2026-07-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0040_remove_profile_added_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
