# Generated by Django 6.0.5 on 2026-07-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0041_delete_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picklistoption',
            unique_together={('company', 'field', 'value')},
        ),
    ]
