# Generated by Django 6.0.5 on 2026-07-28 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0042_alter_picklistoption_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdminApp.deal'),
        ),
    ]
