# Generated by Django 6.0.5 on 2026-07-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0043_alter_task_related_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='related_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='AdminApp.accounts'),
        ),
    ]
