# Generated by Django 6.0.5 on 2026-07-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0045_alter_call_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_to',
        ),
        migrations.AddField(
            model_name='call',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='AdminApp.accounts'),
        ),
        migrations.AddField(
            model_name='task',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='AdminApp.accounts'),
        ),
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='AdminApp.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='AdminApp.deal'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='AdminApp.lead'),
        ),
    ]
