# Generated by Django 6.0.5 on 2026-07-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0046_remove_task_related_to_call_account_task_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='AdminApp.customer'),
        ),
    ]
