# Generated by Django 6.0.5 on 2026-08-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0049_staff_added_by_staff_address_staff_alias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead'), ('task_overdue', 'Task Overdue'), ('meeting_reminder', 'Meeting Reminder'), ('system_update', 'System Update')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AdminApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('email_new_lead_alerts', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=False)),
                ('push_high_priority_tasks', models.BooleanField(default=True)),
                ('push_meeting_reminders', models.BooleanField(default=True)),
                ('inapp_activity_bell', models.BooleanField(default=True)),
                ('inapp_toast_alerts', models.BooleanField(default=True)),
                ('desktop_notification_sound', models.BooleanField(default=False)),
                ('desktop_floating_preview', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='AdminApp.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'user')},
            },
        ),
    ]
