# Generated by Django 6.0.5 on 2026-08-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0051_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_call_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_meeting_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_task_assignments',
            field=models.BooleanField(default=True),
        ),
    ]
