# Generated by Django 6.0.5 on 2026-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0052_notificationpreference_email_call_assignments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('lead_assigned', 'Lead Assigned'), ('deal_assigned', 'Deal Assigned'), ('task_assigned', 'Task Assigned'), ('task_overdue', 'Task Overdue'), ('meeting_reminder', 'Meeting Reminder'), ('invoice_created', 'Invoice Created'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('case_assigned', 'Case Assigned'), ('system_update', 'System Update')], max_length=30),
        ),
    ]
