# Generated by Django 6.0.5 on 2026-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0053_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_case_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_deal_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_invoice_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_purchase_order_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_sales_order_updates',
            field=models.BooleanField(default=True),
        ),
    ]
