# Generated by Django 6.0.5 on 2026-08-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0054_notificationpreference_email_case_assignments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_integrations', to='AdminApp.staff')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_integration', to='AdminApp.company')),
            ],
        ),
    ]
