# Generated by Django 6.0.5 on 2026-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0055_metaintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaintegration',
            name='meta_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
