# Generated by Django 6.0.5 on 2026-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0056_metaintegration_meta_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_lead_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
