# Generated by Django 6.0.5 on 2026-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0057_lead_meta_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaintegration',
            name='page_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
