# Generated by Django 6.0.5 on 2026-09-01 10:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0058_metaintegration_page_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
