# Generated by Django 6.0.5 on 2026-09-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0059_remove_staff_profile_type_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_sid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='call',
            name='error_message',
            field=models.CharField(blank=True, help_text='Populated if Twilio reports a failure (e.g. trial account unverified-number error)', max_length=255),
        ),
        migrations.AddField(
            model_name='call',
            name='from_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='to_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='twilio_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Raw call duration from Twilio, in seconds', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='twilio_status',
            field=models.CharField(blank=True, help_text='Raw status from Twilio: queued, ringing, in-progress, completed, busy, failed, no-answer, canceled', max_length=20),
        ),
    ]
