# Generated by Django 6.0.5 on 2026-09-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0060_call_call_sid_call_error_message_call_from_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=64)),
                ('auth_token_encrypted', models.CharField(max_length=512)),
                ('caller_id', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_settings', to='AdminApp.company')),
            ],
        ),
    ]
