# Generated by Django 6.0.5 on 2026-09-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0060_meetingparticipant_meetingattendeelog'),
        ('AdminApp', '0061_twiliosettings'),
    ]

    operations = [
    ]
