# Generated by Django 6.0.5 on 2026-09-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0064_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='enquiry_type',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('product', 'Product'), ('service', 'Service')], default='not_specified', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_enquiries', to='AdminApp.product'),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_enquiries', to='AdminApp.service'),
        ),
    ]
