# Generated by Django 6.0.5 on 2026-09-18 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0065_lead_enquiry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_notes', to='AdminApp.company')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticky_note', to='AdminApp.staff')),
            ],
        ),
    ]
